#!/bin/sh
# archive indexer

dir="src/archive"
index="${dir}/index.md"
if [ -f ${index} ]; then
	rm ${index}
fi
touch ${index}
echo "% Archive" >> ${index}
echo "" >> ${index}
find ${dir}/*.md -print0 | xargs -0 ls -t | while read f; do
	if [ "${f}" = ${index} ]; then
		continue
	fi
	base=${f%.md}
	echo "* [${base#${dir}/}](${base#src}.html)" >> ${index}
done
echo "indexed archive"