#!/bin/bash

# config
srcdir="src"
destdir="dist"
staticdir="static"
template="src/template.html"

# clean up
rm -rf ${destdir}/
mkdir ${destdir}/

# generate html from markdown
function generate() {
	path=${1}
	file=${path##*/}
	base=${file%.*}
	dest="${destdir}/${base}.html"
	pandoc --template=${template} ${path} > ${dest}
	echo "${dest}"
}

for i in ${srcdir}/*.md ; do
	generate $i
done

# add staticdir to destdir
cp -a ${staticdir}/. ${destdir}/
echo "${destdir}/${staticdir}/"