#!/bin/sh

# https://aweirdimagination.net/2020/06/28/kill-child-jobs-on-script-exit/
cleanup() {
	# kill all processes whose parent is this process
	pkill -P $$
}

for sig in INT QUIT HUP TERM; do
	trap "cleanup trap - $sig EXIT kill -s $sig "'"$$"' "$sig"
done
trap cleanup EXIT

while sleep 0.1; do
	find src static -type f | entr -d ssg -b
done &
httpwatcher --root dist --port 8000 --no-browser &
wait