#!/bin/sh
# micahcowell.com ssg daemon

# https://aweirdimagination.net/2020/06/28/kill-child-jobs-on-script-exit/
cleanup() {
    # kill all processes whose parent is this process
    pkill -P $$
}

for sig in INT QUIT HUP TERM; do
  trap "
    cleanup
    trap - $sig EXIT
    kill -s $sig "'"$$"' "$sig"
done
trap cleanup EXIT

conf="${PWD}/ssg.conf"
if [ -f ${conf} ]; then
	. ${conf}
else
	echo "missing: ${conf}"
	exit 1
fi

archive() {
	while sleep 0.1; do
		find src/archive -type f | entr -d ./archive -i
	done
}

site() {
	while sleep 0.1; do
		find ${SRCDIR} ${STATICDIR} -type f | entr -d ssg -b
	done
}

archive &
site &
httpwatcher --root ${DESTDIR} --port 8000 --no-browser &
wait